/**
 * Report Generator
 *
 * Post-Task 실행 결과를 JSON 및 Markdown 리포트로 생성
 */

import { join } from 'path';
import { mkdir, writeFile, readFile, readdir } from 'fs/promises';
import type {
  PostTaskResult,
  TaskResult,
  ReportFormat,
  ReportMetadata,
  TriggerType,
  TaskType,
} from './post-task-types.js';

/**
 * 리포트 디렉토리 경로
 */
const REPORTS_DIR = '.zyflow/reports/post-task';

/**
 * 리포트 파일명 생성
 */
function generateReportFilename(
  taskType: TaskType | 'all',
  format: ReportFormat
): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  return `${timestamp}_${taskType}.${format === 'json' ? 'json' : 'md'}`;
}

/**
 * JSON 리포트 생성
 */
function generateJSONReport(result: PostTaskResult): string {
  return JSON.stringify(result, null, 2);
}

/**
 * Markdown 리포트 생성
 */
function generateMarkdownReport(result: PostTaskResult): string {
  const lines: string[] = [];

  // 헤더
  lines.push(`# Post-Task Report`);
  lines.push('');
  lines.push(`**Run ID:** \`${result.runId}\``);
  lines.push(`**Started:** ${result.startedAt}`);
  lines.push(`**Finished:** ${result.finishedAt}`);
  lines.push(`**Duration:** ${formatDuration(result.totalDuration)}`);
  lines.push('');

  // 요약
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Tasks | ${result.tasksRun} |`);
  lines.push(`| Succeeded | ${result.tasksSucceeded} |`);
  lines.push(`| Failed | ${result.tasksFailed} |`);
  lines.push(`| Success Rate | ${Math.round((result.tasksSucceeded / result.tasksRun) * 100)}% |`);
  lines.push('');

  // 전체 결과
  lines.push('## Results');
  lines.push('');

  for (const task of result.results) {
    const statusIcon = task.success ? '✅' : '❌';
    lines.push(`### ${statusIcon} ${task.task}`);
    lines.push('');
    lines.push(`- **Status:** ${task.success ? 'Success' : 'Failed'}`);
    lines.push(`- **Duration:** ${formatDuration(task.duration)}`);
    lines.push(`- **Issues Found:** ${task.issuesFound}`);
    lines.push(`- **Issues Fixed:** ${task.issuesFixed}`);
    lines.push(`- **Model:** ${task.model}`);
    lines.push(`- **CLI:** ${task.cli}`);

    if (task.error) {
      lines.push('');
      lines.push('**Error:**');
      lines.push('```');
      lines.push(task.error);
      lines.push('```');
    }

    // 제안
    if (task.details?.suggestions && task.details.suggestions.length > 0) {
      lines.push('');
      lines.push('**Suggestions:**');
      lines.push('');

      for (const suggestion of task.details.suggestions.slice(0, 10)) {
        const confidenceIcon =
          suggestion.confidence === 'high'
            ? '🔴'
            : suggestion.confidence === 'medium'
              ? '🟡'
              : '🟢';
        lines.push(
          `- ${confidenceIcon} **${suggestion.file}**${suggestion.line ? `:${suggestion.line}` : ''}`
        );
        lines.push(`  - Issue: ${suggestion.issue}`);
        lines.push(`  - Suggestion: ${suggestion.suggestion}`);
      }

      if (task.details.suggestions.length > 10) {
        lines.push(`- ... and ${task.details.suggestions.length - 10} more`);
      }
    }

    // 수정된 파일
    if (task.details?.modifiedFiles && task.details.modifiedFiles.length > 0) {
      lines.push('');
      lines.push('**Modified Files:**');
      for (const file of task.details.modifiedFiles) {
        lines.push(`- \`${file}\``);
      }
    }

    // 생성된 파일
    if (task.details?.generatedFiles && task.details.generatedFiles.length > 0) {
      lines.push('');
      lines.push('**Generated Files:**');
      for (const file of task.details.generatedFiles) {
        lines.push(`- \`${file}\``);
      }
    }

    // 격리된 파일
    if (task.details?.quarantinedFiles && task.details.quarantinedFiles.length > 0) {
      lines.push('');
      lines.push('**Quarantined Files:**');
      for (const file of task.details.quarantinedFiles) {
        lines.push(`- \`${file}\``);
      }
    }

    lines.push('');
  }

  // 푸터
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by ZyFlow Post-Task Agent*`);

  return lines.join('\n');
}

/**
 * 시간 포맷팅
 */
function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(2)}s`;
  return `${(ms / 60000).toFixed(2)}m`;
}

/**
 * 리포트 저장
 */
export async function saveReport(
  projectPath: string,
  result: PostTaskResult,
  format: ReportFormat = 'markdown',
  triggerType: TriggerType = 'manual'
): Promise<{ success: boolean; path: string }> {
  const reportsDir = join(projectPath, REPORTS_DIR);

  try {
    // 디렉토리 생성
    await mkdir(reportsDir, { recursive: true });

    // 작업 타입 결정
    const taskTypes = result.results.map((r) => r.task);
    const taskType = taskTypes.length === 1 ? taskTypes[0] : 'all';

    // 파일명 생성
    const filename = generateReportFilename(taskType, format);
    const filepath = join(reportsDir, filename);

    // 리포트 생성
    const content =
      format === 'json'
        ? generateJSONReport(result)
        : generateMarkdownReport(result);

    // 저장
    await writeFile(filepath, content, 'utf-8');

    return {
      success: true,
      path: filepath.replace(projectPath + '/', ''),
    };
  } catch (error) {
    console.error('Failed to save report:', error);
    return {
      success: false,
      path: '',
    };
  }
}

/**
 * 리포트 목록 조회
 */
export async function listReports(
  projectPath: string,
  options?: { limit?: number; taskType?: TaskType }
): Promise<ReportMetadata[]> {
  const reportsDir = join(projectPath, REPORTS_DIR);
  const reports: ReportMetadata[] = [];

  try {
    const files = await readdir(reportsDir);

    for (const file of files) {
      // 파일명 파싱: 2024-12-13T10-30-00_lint-fix.json
      const match = file.match(/^(\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2})_([^.]+)\.(json|md)$/);

      if (match) {
        const timestamp = match[1].replace(/-/g, ':').replace('T', 'T');
        const taskType = match[2] as TaskType | 'all';
        const format = match[3] as ReportFormat;

        // 필터링
        if (options?.taskType && taskType !== options.taskType && taskType !== 'all') {
          continue;
        }

        reports.push({
          id: file.replace(/\.(json|md)$/, ''),
          createdAt: timestamp,
          taskType,
          triggerType: 'manual', // 파일에서 추출 불가
          format: format === 'json' ? 'json' : 'markdown',
          filePath: join(REPORTS_DIR, file),
        });
      }
    }

    // 최신순 정렬
    reports.sort((a, b) => b.createdAt.localeCompare(a.createdAt));

    // 제한
    if (options?.limit) {
      return reports.slice(0, options.limit);
    }

    return reports;
  } catch {
    return [];
  }
}

/**
 * 리포트 조회
 */
export async function getReport(
  projectPath: string,
  reportId: string
): Promise<{ metadata: ReportMetadata; content: string } | null> {
  const reports = await listReports(projectPath);
  const metadata = reports.find((r) => r.id === reportId);

  if (!metadata) {
    return null;
  }

  try {
    const content = await readFile(join(projectPath, metadata.filePath), 'utf-8');
    return { metadata, content };
  } catch {
    return null;
  }
}

/**
 * 주간 요약 리포트 생성
 */
export async function generateWeeklySummary(
  projectPath: string
): Promise<{ success: boolean; path?: string }> {
  const reports = await listReports(projectPath);

  // 최근 7일간 리포트 필터링
  const weekAgo = new Date();
  weekAgo.setDate(weekAgo.getDate() - 7);

  const weeklyReports = reports.filter((r) => {
    const reportDate = new Date(r.createdAt.replace(/-/g, ':'));
    return reportDate >= weekAgo;
  });

  if (weeklyReports.length === 0) {
    return { success: false };
  }

  // 통계 계산
  const stats = {
    totalRuns: weeklyReports.length,
    byTask: {} as Record<string, number>,
    totalIssuesFound: 0,
    totalIssuesFixed: 0,
  };

  for (const report of weeklyReports) {
    stats.byTask[report.taskType] = (stats.byTask[report.taskType] || 0) + 1;

    // JSON 리포트에서 상세 통계 추출
    if (report.format === 'json') {
      try {
        const content = await readFile(join(projectPath, report.filePath), 'utf-8');
        const data = JSON.parse(content) as PostTaskResult;

        for (const result of data.results) {
          stats.totalIssuesFound += result.issuesFound;
          stats.totalIssuesFixed += result.issuesFixed;
        }
      } catch {
        // 무시
      }
    }
  }

  // 주간 요약 생성
  const weekNumber = getWeekNumber(new Date());
  const lines: string[] = [];

  lines.push(`# Weekly Summary - Week ${weekNumber}`);
  lines.push('');
  lines.push(`**Period:** ${weekAgo.toISOString().split('T')[0]} - ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  lines.push('## Overview');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Runs | ${stats.totalRuns} |`);
  lines.push(`| Issues Found | ${stats.totalIssuesFound} |`);
  lines.push(`| Issues Fixed | ${stats.totalIssuesFixed} |`);
  lines.push(`| Fix Rate | ${stats.totalIssuesFound > 0 ? Math.round((stats.totalIssuesFixed / stats.totalIssuesFound) * 100) : 0}% |`);
  lines.push('');

  lines.push('## By Task Type');
  lines.push('');
  lines.push(`| Task | Runs |`);
  lines.push(`|------|------|`);

  for (const [task, count] of Object.entries(stats.byTask).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${task} | ${count} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by ZyFlow Post-Task Agent*`);

  // 저장
  const summaryDir = join(projectPath, '.zyflow/reports/summary');
  await mkdir(summaryDir, { recursive: true });

  const filename = `weekly-${new Date().getFullYear()}-W${weekNumber}.md`;
  const filepath = join(summaryDir, filename);

  await writeFile(filepath, lines.join('\n'), 'utf-8');

  return {
    success: true,
    path: filepath.replace(projectPath + '/', ''),
  };
}

/**
 * ISO 주차 계산
 */
function getWeekNumber(date: Date): number {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
}
